import { test, expect } from "@playwright/test";
test("offline badge demo onnx work remote disabled", async ({ page, context }) => {
  await page.goto("/");
  await expect(page.getByTestId("dashboard")).toBeVisible({ timeout: 30000 });
  await expect(page.getByTestId("map-view")).toBeVisible({ timeout: 30000 });
  await expect(page.getByTestId("recon-panel")).toBeVisible({ timeout: 30000 });
  await page.reload();
  await expect(page.getByTestId("dashboard")).toBeVisible({ timeout: 30000 });
  await expect(page.getByTestId("recon-panel")).toBeVisible({ timeout: 30000 });
  await context.setOffline(true);
  await page.goto("/", { waitUntil: "domcontentloaded" }).catch(() => undefined);
  await expect(page.locator("text=OFFLINE MODE").first()).toBeVisible({ timeout: 30000 });
  await expect(page.getByTestId("map-view")).toBeVisible({ timeout: 30000 });
  await expect(page.getByTestId("profile-chart")).toBeVisible({ timeout: 30000 });
  const engineHtml = await page.locator("#rc-engine").innerHTML();
  expect(engineHtml.indexOf("remote")).toBeGreaterThan(-1);
  await page.locator("#rc-engine").selectOption("demo");
  await page.getByTestId("run-btn").click();
  await expect(page.getByTestId("recon-panel")).toBeVisible({ timeout: 30000 });
  await page.locator("#rc-engine").selectOption("remote");
  await page.getByTestId("run-btn").click();
  await expect(page.getByTestId("run-error")).toContainText("offline", { timeout: 15000 });
  await context.setOffline(false);
});
